# Generated by Django 4.1.1 on 2022-09-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_rename_leads_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
