# Generated by Django 4.1.1 on 2022-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0004_userprofile_agent_orgarnization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_orgarnizer',
            field=models.BooleanField(default=True),
        ),
    ]
